### ISSUE TITLE
"break" should be "continue" [ in Statistical/primitivesCleanUp.m]

### ISSUE THREAD

**Issue by drinkcor** [birlrobotics/RCBHT#6]
In line 152.

   if(ampRatio > amplitudeRatio || ampRatio < inv(amplitudeRatio)) 
                break;                                              % If this is true, don't do anything else.

If these two primitives couldn't be merged, we should do nothing to them. Even so, we still need to continue the loop to clean up the rest of primitives.

**Comment by rojas70** [comment]
Fixed. Thanks
